#!/usr/bin/python3
import pygame as pg
import fileinput

from math import *

pg.init()                                 # inicialização do sistema

# altura e largura da arena, em células
H, W = 13,13
# largura da célula
l = 30
# altura da célula
L = 2*l/sqrt(3)

# cria a janela
scr = pg.display.set_mode((2*W*l+l,int(1.5*L*H+L/2)))
# só para simplificar, atualização da imagem
atu = pg.display.update


# pinta o fundo da janela
scr.fill((0,0,0))
atu()

def convert(i ,j):
    """
    Converte a coordenada (i,j) para a posição em pixels na janela
    """
    x = (1 + i%2)*l + 2*j*l
    y = 1.5*i*L + L
    return x,y

class Robô(pg.sprite.Sprite):
    """
    Representa um Robô, possui uma imagem
    """
    def __init__(s, img):
        """
        Construtor, img é o nome do arquivo com a imagem
        """
        pg.sprite.Sprite.__init__(s)
        s.image = pg.image.load(img)
        s.rect = s.image.get_rect()

    def draw(s, i,j):
        """
        Desenha o robô na célula (i,j)
        """
        x, y = convert(i,j)

        # fronteiras do sprite
        l0,h0,l1,h1 = s.rect

        # corrije a posição de acordo com o tamanho do sprite
        s.rect.topleft = [x-l1/2,y-h1/2]
        # desenha
        scr.blit(s.image, s.rect)


class Base(pg.sprite.Sprite):
    """
    Representa uma Base, possui uma imagem
    """
    def __init__(s, img):
        """
        Construtor, img é o nome do arquivo com a imagem
        """
        pg.sprite.Sprite.__init__(s)
        s.image = pg.image.load(img)
        s.rect = s.image.get_rect()

    def draw(s, i,j):
        """
        Desenha a base na célula (i,j)
        """
        x, y = convert(i,j)

        # fronteiras do sprite
        l0,h0,l1,h1 = s.rect

        # corrije a posição de acordo com o tamanho do sprite
        s.rect.topleft = [x-l1/2,y-h1/2]
        # desenha
        scr.blit(s.image, s.rect)

    
class Cell:
    """
    Representa uma das células da arena
    """
    def __init__(s,i,j,r,g,b):
        """
        Construtor, i e j formam a coordenada
        """
        # Posição do centro
        s.cx, s.cy = convert(i,j)
        # Cor (pode ser passada para o construtor no futuro)
        s.cor = (r,g,b)
        s.cristais = 0
        # Vértices do hexágono
        s.pontos = (
            (s.cx,   s.cy-L),
            (s.cx+l, s.cy-L/2),
            (s.cx+l, s.cy+L/2),
            (s.cx,   s.cy+L),
            (s.cx-l, s.cy+L/2),
            (s.cx-l, s.cy-L/2),
            )
        
    def draw(s) :
        """
        Desenha a célula
        """
        pg.draw.polygon(scr, s.cor, s.pontos, 0)
        pg.draw.lines(scr, (0,0,0), True, s.pontos, 2)

class Cristais(pg.sprite.Sprite):
    """
    Representa os Cristais, possui imagens
    """
    def __init__(s):
        pg.sprite.Sprite.__init__(s)

    def draw(s, i, j, n):
        """
        Desenha os cristais na célula (i,j)
        """
        if n > 0:
            x, y = convert(i,j)
            if n >5: img = 'salt'+ str(5) + '.png'
            else:    img = 'salt'+ str(n) + '.png'
            s.image = pg.image.load(img)
            s.rect = s.image.get_rect()
            # fronteiras do sprite
            l0,h0,l1,h1 = s.rect
            # corrije a posição de acordo com o tamanho do sprite
            s.rect.topleft = [x-l1/2,y-h1/2]
            # desenha
            scr.blit(s.image, s.rect)


# Construção da matriz que representa a arena
arena = []
for i in range(H):
    arena.append([])
    for j in range(W):
        arena[i].append(Cell(i,j,125,125,125))
        arena[i][j].draw()

# lista dos robôs definidos
robs = []
bases = []
cristais = []
cristais.append(Cristais())
# atualiza a janela
atu()

# Leitura dos comandos pela entrada padrão ou de um arquivo
for line in fileinput.input():
    r = line.split()

    # linha começando com 'fim', termina o programa
    if r[0] == 'fim':
        break

    # linha começando com 'rob', inclui um robô,
    # o segundo argumento na linha é a imagem   
    if r[0] == 'rob':
        robs.append(Robô(r[1]))
        i, j = list(map(int,r[2:]))
        robs[-1].draw(i,j)
        continue

    if r[0] == 'base':
        bases.append(Base(r[1]))
        i, j = list(map(int,r[2:]))
        bases[-1].draw(i,j)
        continue

    if r[0] == 'atk':
        rid,i, j = list(map(int,r[3:]))
        robs[ri].image = pg.image.load(r[1])
        arena[i][j].draw()
        robs[ri].draw(i,j)
        atu()
        pg.time.wait(2000)
        arena[i][j].draw()
        robs[ri].image = pg.image.load(r[2])
        robs[ri].draw(i,j)
        atu()
        continue

    if r[0] == 'destroy':
        base,i, j = list(map(int,r[2:]))
        bases[base].image = pg.image.load(r[1])
        arena[i][j].draw()
        bases[base].draw(i,j)
        atu()
        pg.time.wait(10)
        continue  

    if r[0] == 'cristais':
        n, i, j = list(map(int, r[1:]))
        arena[i][j].cristais = n
        arena[i][j].draw()
        cristais[0].draw(i,j,n)
        atu()
        pg.time.wait(10)
        continue
    if r[0] == 'cell':
        i, j, r, g ,b = list(map(int, r[1:]))
        arena[i][j].cor = (r,g,b)
        arena[i][j].draw()
        atu()
        pg.time.wait(10)
        continue
    # linha de movimentação:
    # robô, corrdenadas originais, coordenadas finais
    ri, oi, oj, di, dj = list(map(int, r))

    # redesenha a célula original (apaga o robô)
    if 0 <= oi  < W and 0 <= oj < H:
        arena[oi][oj].draw()
        cristais[0].draw(oi,oj,arena[oi][oj].cristais)
    # desenha o robô na célula de destino
    if 0 <= di  < W and 0 <= dj < H and ri < len(robs):
        robs[ri].draw(di,dj)
    # tempo de espera para atualização, apenas para testes

    atu()

    pg.time.wait(300)


pg.time.wait(10000)
pg.quit()
# Local variables:
# mode: python
# End:
